#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# clixtragen - generates helpers for a command line interpreter
#
# Copyright (C) 2013 Eric Le Bihan
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

import argparse
from gettext import gettext as _
from clixtragen import __version__
from clixtragen.utils import setup_i18n
from clixtragen.parsers import PythonParser
from clixtragen.generators import ZshCompletionGenerator

setup_i18n()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version')
    parser.add_argument('progname',
                        help=_('name of the program'))
    parser.add_argument('filename',
                        help=_('source file to parse'))
    parser.add_argument('-o', '--output',
                        metavar='FILE',
                        help=_('set output filename'))

    args = parser.parse_args()

    parser = PythonParser()
    progargs, progopts = parser.parse_file(args.filename)

    generator = ZshCompletionGenerator()
    text = generator.generate(args.progname, progargs, progopts)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(text)
    else:
        print(text, end='')

# vim: ts=4 sts=4 sw=4 et ai
